### ISSUE TITLE
Doesn't work with rollup-plugin-multi-entry

### ISSUE THREAD

**Issue by Kflash** [artberri/rollup-plugin-istanbul#9] opened 2016-05-22 22:44 UTC
This plugin doesn't work with rollup-plugin-multi-entry. Gives tons of errors

**Comment by artberri** [comment] 2016-05-25 16:24
Which errors? are you sure that the problem is this plugin? How can I reproduce the error?

I'll close this, please check this issue before opening a new one: https://github.com/artberri/rollup-plugin-istanbul/issues/8

**Closed by artberri** 2016-05-25 16:24 UTC

**Comment by Kflash** [comment] 2016-05-25 19:35
Simply add this multi entry plugin to the script, and run istanbul. Tons of error msg

**Comment by artberri** [comment] 2016-05-26 07:35
Hi,

Please read any post about best practises reporting bugs, for example:
http://www.panopticdev.com/blog/7-best-practices-bug-reporting/

Tons of errors? Paste them here. Describe the steps to reproduce the error, paste your package.json, paste your Grunt/Gulp file, or the command you use to run it...

If we have a bug we want to fix it, but you need to explain it better.

Rigards.

**Comment by Kflash** [comment] 2016-05-26 07:48
Let's take a live example from one of my boilerplates. 

https://github.com/Kflash/farris/blob/master/config/karma.conf.js

If I try to use the multi entry plugin here, a lot of errors will occur.

Or this boilerplate where Babel are used:

https://github.com/Kflash/spiky/blob/master/config/karma.conf.babel.js#L31

Same thing happen for both of them, so the multi entry are taken out.

Maybe you will say I used the multi entry plugin in wrong order, but then have a look at this
https://github.com/google/incremental-dom/blob/master/conf/karma.conf.js#L38

Last one is configured by the author of Rollup - Rich Harris - himself. So the order is correct.

It also seem to be issues with the config
`sourceMap: 'inline'`, but yet to verify that one. You see how Mr. Harris configured that one.

So this is the errors to reproduce.

Tons of errors? Well. The whole console was covered with errors.

If I'm sure this is a plugin error? Can never say never, but I'm 87% sure.
Another rollup plugin - filesize() - gives tons of errors in a combination with  `sourceMap: 'inline'` so I narrowed that done to be an issue there. 

And I also tested this with both Istanbul and babel-Istanbul. Babel-istanbul have more ES2015 features so my first thought it was something wrong with Istanbul plugin. But both throws errors when it comes to multi entry.

Your plugin also throws other errors, but I narrowed that down to be the Istanbul plugins lack of ES2015 features ( babel-istanbul worked).

**Comment by Kflash** [comment] 2016-05-26 07:53
You can also try to install your plugin on Mr. Harris own configuration as
I linked too. And you will trigger the same errors - IF you get it working
there !

**Comment by Kflash** [comment] 2016-05-26 08:17
```
26 05 2016 16:15:51.988:ERROR [coverage]: { Error: ENOENT: no such file or directory, open 'C:\xampp4\htdocs\farris\rollup-plugin-multi-entry:entry-point'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at LookupStore.Store.mix.get (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\store\fslookup.js:40:19)
    at HtmlReport.Report.mix.writeDetailPage (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\html.js:411:67)
    at C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\html.js:489:26
    at SyncFileWriter.extend.writeFile (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\util\file-writer.js:57:9)
    at FileWriter.extend.writeFile (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\util\file-writer.js:147:23)
    at C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\html.js:488:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\html.js:482:23)
    at C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\html.js:484:22
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\html.js:482:23)
    at HtmlReport.Report.mix.writeReport (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\html.js:566:14)
    at LcovReport.Report.mix.writeReport (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\lcov.js:55:19)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\xampp4\\htdocs\\farris\\rollup-plugin-multi-entry:entry-point' }
Error: ENOENT: no such file or directory, open 'C:\xampp4\htdocs\farris\rollup-plugin-multi-entry:entry-point'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at LookupStore.Store.mix.get (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\store\fslookup.js:40:19)
    at HtmlReport.Report.mix.writeDetailPage (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\html.js:411:67)
    at C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\html.js:489:26
    at SyncFileWriter.extend.writeFile (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\util\file-writer.js:57:9)
    at FileWriter.extend.writeFile (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\util\file-writer.js:147:23)
    at C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\html.js:488:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\html.js:482:23)
    at C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\html.js:484:22
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\html.js:482:23)
    at HtmlReport.Report.mix.writeReport (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\html.js:566:14)
    at LcovReport.Report.mix.writeReport (C:\xampp4\htdocs\farris\node_modules\istanbul\lib\report\lcov.js:55:19)

```

Took me 2 seconds to trigger it

**Comment by artberri** [comment] 2016-05-26 15:21
Just because adding this plugin you get an error doesn't mean that the problem is this plugin. I would say, why the plugin with the problem is not the multi-entry one?

I have been trying also to explain you that you need to make easy my work if you want me to support your problem. What are the steps to reproduce the error, which command you are running? Instead of explaining and give an step-by-step guide to do it you have just put some links.

In spite of this situation, I have been trying to solve your problem. You should be able to see a solution on this fork: https://github.com/artberri/farris/blob/poc-rollup-istanbul/config/karma.conf.js#L52

I'm pretty sure that the problem is related to `rollup-plugin-multi-entry` which is changing some rollup parameters without taking into account that other plugins will be affected. But you can solve it just ensuring that you include only *.js files as you can see in the above link.

It was a bit tricky to find it because you didn't paste here all the commands and the whole console output, where you can see that the istanbul plugin is trying to make the coverage of non existing files:

```
----------------------------------------|----------|----------|----------|----------|----------------|
File                                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------------------------------|----------|----------|----------|----------|----------------|
 __root__/                              |      100 |      100 |      100 |      100 |                |
  rollup-plugin-multi-entry:entry-point |      100 |      100 |      100 |      100 |                |
 home/avarela/projects/farris/src/      |      100 |      100 |      100 |      100 |                |
  index.js                              |      100 |      100 |      100 |      100 |                |
----------------------------------------|----------|----------|----------|----------|----------------|
All files                               |      100 |      100 |      100 |      100 |                |
----------------------------------------|----------|----------|----------|----------|----------------|
```

I will like you to understand that this is free software and I'm maintaining this in my spare time just because I want. I don't earn money with it, and, of course, I'm not required to support anybody. if you find a bug/issue you can contribute, solve it and make a pull request, if it's important for you and you are in a rush you should do it (instead of putting pressure on me or said that my project is dead just because I didn't answer you in a couple of weeks).

I like when the people use my software and I like to help them, but I will not allow requirements or pressure from them.

Sorry if I've been rude, but it has been quite annoying.
