### ISSUE TITLE
Unable to generate full lcov HTML, incorrect line numbers

### ISSUE THREAD

**Issue by kmck** [artberri/rollup-plugin-istanbul#12] opened 2016-10-02 05:59 UTC
Hi there! Digging this plugin, but I'm having two issues.

First, I'm unable to generate full lcov files. I get `TypeError: Cannot read property 'text' of undefined` when I try to run it. When I change `logLevel` to `config.LOG_DISABLE`, it doesn't error anymore, but I only get an `index.html`, not the full report for the source files.

Second, I think the line numbers are off. I'm not exactly sure how, but I imagine it's basing the line numbers off some intermediate bundled state rather than the source file. I noticed because I was trying to write tests for uncovered lines and realized that it was calling out line numbers that were beyond the end of the file, heh.

Here's my `karma.config.js`:

``` js
const json = require('rollup-plugin-json');
const babel = require('rollup-plugin-babel');
const nodeResolve = require('rollup-plugin-node-resolve');
const istanbul = require('rollup-plugin-istanbul');

module.exports = (config) => {
  config.set({
    basePath: '',
    frameworks: ['mocha', 'chai', 'sinon'],
    files: [
      'node_modules/babel-polyfill/dist/polyfill.js',
      'test/**/*.test.js',
    ],
    exclude: [],

    preprocessors: {
      'test/**/*.js': ['rollup'],
    },
    rollupPreprocessor: {
      plugins: [
        json(),
        babel(),
        nodeResolve({ jsnext: true }),
        istanbul({
          include: 'src/WKPostMessenger.js',
        }),
      ],
      // will help to prevent conflicts between different tests entries
      sourceMap: 'inline',
    },

    reporters: ['mocha', 'coverage'],
    coverageReporter: {
      dir: 'coverage',
      reporters: [{
      //   type: 'lcov',
      //   subdir: '.',
      // }, {
      //   type: 'json',
      //   subdir: '.',
      //   file: 'coverage-final.json',
      // }, {
        type: 'text',
      }],
    },

    plugins: [
      'karma-phantomjs-launcher',
      'karma-rollup-plugin',
      'karma-mocha',
      'karma-mocha-reporter',
      'karma-chai',
      'karma-sinon',
      'karma-coverage',
    ],

    port: 9876,
    colors: true,
    captureConsole: true,
    logLevel: config.LOG_INFO,
    autoWatch: false,
    browsers: ['PhantomJS'],
    singleRun: true,
    concurrency: Infinity,
  });
};
```

**Comment by jlmakes** [comment] 2016-11-23 17:36
@kmck I tried browserify with istanbul before moving to rollup, and they mentioned a coverage bug that was fixed by using `instrumenterConfig: { embedSource: true }`.

I had line number issues like you described with `rollup-plugin-istanbul`, but I fixed them by adding that same option to the instrumenter config.

_Example_:
```js
rollupPreprocessor: {
  plugins: [
    json(),
    babel(),
    nodeResolve({ jsnext: true }),
    istanbul({
      include: 'src/WKPostMessenger.js',
      instrumenterConfig: {
        embedSource: true,
      },
    }),
  ],
  // will help to prevent conflicts between different tests entries
  sourceMap: 'inline',
},
```

Give that a try!

**Comment by kmck** [comment] 2016-11-26 02:03
Nice workaround! The coverage report shows the transpiled source, which is kind of a bummer, but this is definitely an improvement, so thank you!

**Comment by jlmakes** [comment] 2016-12-29 04:09
@kmck Can you try my fork? I'm working on a PR...
https://github.com/jlmakes/rollup-plugin-istanbul

**Comment by kmck** [comment] 2016-12-29 17:38
@jlmakes hey, that looks pretty good! I didn't dig too deeply into it (eg. re-uncovering some lines and verifying that the correct source line numbers were flagged), but the generated report has the ES6 source code and appears to be correct at a glance.

I had to jump through some hoops to get the fork set up from Github, which I'll list for the benefit of anyone else following along:

1. `npm install jlmakes/rollup-plugin-istanbul`
2. `cd node_modules/rollup-plugin-istanbul`
3. **Problem:** Missing `dist/` files that only get packaged when publishing to `npm`
    * **Fix:** `curl https://raw.githubusercontent.com/artberri/rollup-plugin-istanbul/master/rollup.config.js > rollup.config.js` to get `rollup.config.js` back
4. **Problem:** Missing `rollup.config.js` because `package.json` excludes it from `files`
    * **Fix:** `npm run build` to build the `dist/` files
5. Success!

**Comment by jlmakes** [comment] 2016-12-29 19:37
Nice! Thanks for taking the time @kmck.

The current version of Istanbul is no longer maintained, so the fork I've used that appears to fix the issue is on top of the latest version of Istanbul 1.0... 

I think this is the best we're going to get, until upgrading `rollup-plugin-istanbul` to use version 2.0.

**Comment by Shyam-Chen** [comment] 2017-10-09 13:08
```js
// rollup
[...]
     exclude: join(SOURCE_ROOT, '**/*.spec.js'),
      instrumenterConfig: {
        embedSource: true
      }
    })
[...]
```

```js
// karma
[...]
    reporters: ['mocha', 'coverage-istanbul'],
    coverageIstanbulReporter: {
      reports: ['html', 'lcovonly', 'text-summary'] . // error with lcovonly
    },
[...]
```

[karma]: TypeError: Cannot read property 'start' of undefined

**Comment by artberri** [comment] 2017-12-07 15:21
Sorry for being late answering here.

The new v2.0.0 version uses now the new istanbul instrumenter. Please double check if you keep suffering the error.

**Closed by artberri** 2017-12-07 15:21 UTC
